// This is generated by CMake; re-run to actualize.
// Feb 19 2025, 19:33:14Z

#pragma once

#include <QString>

namespace yangl {

static const struct VersionInfo {

    const int Major { 1 } ;
    const int Minor { 0 } ;
    const int Patch { 0 } ;

    const QString Branch { QStringLiteral("dengof_switch_to_cmake") } ;
    const QString CommitFull { QStringLiteral("f7b1bb94de4e739331b0e7d9618df77d6f85c37c") } ;
    const QString Commit { QStringLiteral("f7b1bb9") } ;
    const qint64 BuildDateSeconds { 1739993594 } ; // UTC
    const bool BranchDirty { 1 } ;

    QString majorMinor() const;
    QString trio() const;
    QString commit() const;
    QString buildDate(const QString& format) const;

} V = {};

}  // namespace yangl
