// This is generated by CMake; re-run to actualize.
// Feb 19 2025, 15:16:03Z

#pragma once

#include <QString>

namespace yangl {

struct VersionInfo {

    const int Major { 1 } ;
    const int Minor { 0 } ;
    const int Patch { 0 } ;

    const QString Branch { QStringLiteral("dengof_switch_to_cmake") } ;
    const QString CommitFull { QStringLiteral("d4dab469a373fe4c9022083ae6726b639112c11e") } ;
    const QString Commit { QStringLiteral("d4dab46") } ;
    const qint64 BuildDateSeconds { 1739978163 } ; // UTC
    const bool BranchDirty { 1 } ;

    QString majorMinor() const;
    QString trio() const;
    QString commit() const;
    QString buildDate(const QString& format) const;

};

// Instance declaration for the static version info, it should be outside the struct
extern const VersionInfo V;

}  // namespace yangl
